# Generated by Django 4.2.29 on 2026-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiary',
            name='bee_info',
            field=models.TextField(blank=True, null=True, verbose_name='Данные о пчелосемье'),
        ),
        migrations.AddField(
            model_name='apiary',
            name='hive_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор улья'),
        ),
    ]
