# Generated by Django 4.2.29 on 2026-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0002_apiary_bee_info_apiary_hive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='bee_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hive',
            name='hive_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
